### PR TITLE
Allow html in captions

### PR DESCRIPTION
**Pull request by michakrapp**
since you overwrite this from wp-featherlight.
See https://github.com/wpsitecare/wp-featherlight/issues/33

### CODE REVIEW

**Comment by michakrapp** [comment]
Since https://github.com/wpsitecare/wp-featherlight/pull/38 has been merged and https://github.com/wpsitecare/wp-featherlight/issues/33 was closed maybe you could merge it too?

I did not update the minified versions, just the helper-js.

**Comment by michakrapp** [comment]
Any change for merging this and releasing an update to the plugin?

**Comment by tyrann0us** [comment]
Hi @michakrapp,
sorry for the delay! I didn't get a notification about your PR.

I'm about to release v0.5. Since this PR doesn't include the minified version, I'll close it and include the change manually.

Thanks for your work!

**Comment by michakrapp** [comment]
Thanks for the Plugin update. HTML in Captions work

**Pull request closed without merging**
